[package]
name = "time_complexity"
version = "0.1.0"
authors = ["jeremylt <jeremy@jeremylt.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
